### ISSUE TITLE
Private Submodule vanetza

### ISSUE THREAD

**Issue by Enough7** [ibr-cm/a4md#1]
Hi,

the git submodule `vanetza` is private eg. git asks for a password. 

Edit: A custom `vanetza` seems to have been used here

**Comment by awillecke** [comment]
Hi,

thank you for noticing! It should be fixed with [7e4d871](https://github.com/ibr-cm/a4md/commit/7e4d871b88d4e9db0e8b23f6ff45787d8b33c52d).

Best regards
